// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "uala-challenge/internal/model"
)

// GetTimelineUseCase is an autogenerated mock type for the getTimelineUseCase type
type GetTimelineUseCase struct {
	mock.Mock
}

// GetTimeline provides a mock function with given fields: ctx, userID
func (_m *GetTimelineUseCase) GetTimeline(ctx context.Context, userID string) (*model.Timeline, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeline")
	}

	var r0 *model.Timeline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Timeline, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Timeline); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Timeline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetTimelineUseCase creates a new instance of GetTimelineUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetTimelineUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetTimelineUseCase {
	mock := &GetTimelineUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
