// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "uala-challenge/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// TimelineRepository is an autogenerated mock type for the timelineRepository type
type TimelineRepository struct {
	mock.Mock
}

// UpdateTimelinesForTweet provides a mock function with given fields: ctx, tweet, followers
func (_m *TimelineRepository) UpdateTimelinesForTweet(ctx context.Context, tweet *model.Tweet, followers []string) error {
	ret := _m.Called(ctx, tweet, followers)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTimelinesForTweet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Tweet, []string) error); ok {
		r0 = rf(ctx, tweet, followers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTimelineRepository creates a new instance of TimelineRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimelineRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimelineRepository {
	mock := &TimelineRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
