// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "uala-challenge/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// TweetRepository is an autogenerated mock type for the tweetRepository type
type TweetRepository struct {
	mock.Mock
}

// CreateTweet provides a mock function with given fields: ctx, tweet
func (_m *TweetRepository) CreateTweet(ctx context.Context, tweet *model.Tweet) error {
	ret := _m.Called(ctx, tweet)

	if len(ret) == 0 {
		panic("no return value specified for CreateTweet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Tweet) error); ok {
		r0 = rf(ctx, tweet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTweetRepository creates a new instance of TweetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTweetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TweetRepository {
	mock := &TweetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
