// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "uala-challenge/internal/model"
)

// CreateTweetUseCase is an autogenerated mock type for the createTweetUseCase type
type CreateTweetUseCase struct {
	mock.Mock
}

// CreateTweet provides a mock function with given fields: ctx, tweet
func (_m *CreateTweetUseCase) CreateTweet(ctx context.Context, tweet *model.Tweet) error {
	ret := _m.Called(ctx, tweet)

	if len(ret) == 0 {
		panic("no return value specified for CreateTweet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Tweet) error); ok {
		r0 = rf(ctx, tweet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCreateTweetUseCase creates a new instance of CreateTweetUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateTweetUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateTweetUseCase {
	mock := &CreateTweetUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
